import React, { useState } from 'react';
import type { TriageResult } from '../types';

interface DoctorReferralReportProps {
  result: TriageResult;
  symptomsInput: string;
  onClose: () => void;
}

export const DoctorReferralReport: React.FC<DoctorReferralReportProps> = ({
  result,
  symptomsInput,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);
  const refId = `REF-${new Date().getFullYear()}${(new Date().getMonth() + 1).toString().padStart(2, '0')}${new Date().getDate().toString().padStart(2, '0')}-${Math.floor(1000 + Math.random() * 9000)}`;
  const timestamp = new Date().toLocaleString('en-US', {
    dateStyle: 'full',
    timeStyle: 'short',
  });

  const topPrediction = result.predictions[0] || {
    disease: 'Undetermined',
    confidence: 0,
    severity: 'low',
    specialty: 'General Physician',
  };

  const isHighSeverity = topPrediction.severity.toLowerCase() === 'high';

  const handlePrint = () => {
    window.print();
  };

  const handleCopyToClipboard = () => {
    const textSummary = `
=====================================================
🏥 MEDTRIAGE AI — CLINICAL REFERRAL REPORT
=====================================================
Reference ID: ${refId}
Date & Time: ${timestamp}

1. CHIEF COMPLAINT / REPORTED SYMPTOMS:
"${symptomsInput}"

2. CLINICAL SEVERITY ASSESSMENT:
- Urgency Level: ${topPrediction.severity.toUpperCase()}
- Detected Keywords: ${result.detected_symptoms.join(', ') || 'None flagged'}

3. AI VECTOR DB DIFFERENTIAL DIAGNOSIS:
${result.predictions.map((p, i) => `   [${i + 1}] ${p.disease} (Confidence: ${(p.confidence * 100).toFixed(1)}%, Specialty: ${p.specialty})`).join('\n')}

4. RECOMMENDED SPECIALIST REFERRAL:
-> ${topPrediction.specialty}

5. HISTORICAL CASE EVIDENCE (TOP MATCHES):
${result.similar_cases.slice(0, 3).map((c) => `   - Case #${c.case_id}: ${c.disease} (${(c.similarity * 100).toFixed(1)}% match)`).join('\n')}

=====================================================
* Generated by MedTriage AI Multilingual Healthcare Triage System.
* This document is for clinical referral and triage guidance.
=====================================================
    `.trim();

    navigator.clipboard.writeText(textSummary);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/70 backdrop-blur-sm animate-fade-in overflow-y-auto">
      {/* Print Specific Styles */}
      <style>{`
        @media print {
          body * {
            visibility: hidden !important;
          }
          #printable-report, #printable-report * {
            visibility: visible !important;
          }
          #printable-report {
            position: absolute !important;
            left: 0 !important;
            top: 0 !important;
            width: 100% !important;
            max-width: 100% !important;
            margin: 0 !important;
            padding: 30px !important;
            box-shadow: none !important;
            border: none !important;
            background: white !important;
            color: black !important;
          }
          .no-print {
            display: none !important;
          }
        }
      `}</style>

      <div className="relative w-full max-w-4xl bg-slate-900 border border-slate-800 rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Modal Action Bar (Hidden when printing) */}
        <div className="no-print p-4 sm:p-5 bg-slate-800/80 border-b border-slate-700/80 flex flex-wrap items-center justify-between gap-3 sticky top-0 z-10 backdrop-blur-md">
          <div className="flex items-center gap-2">
            <span className="text-xl">📄</span>
            <div>
              <h3 className="font-bold text-sm text-white">Doctor's Referral Report Preview</h3>
              <span className="text-[11px] text-slate-400">Ready for print or PDF export</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyToClipboard}
              className="px-4 py-2 rounded-xl text-xs font-bold bg-slate-700 hover:bg-slate-600 text-white transition-all flex items-center gap-1.5"
            >
              <span>{copied ? '✅' : '📋'}</span>
              <span>{copied ? 'Copied to Clipboard!' : 'Copy Text'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-5 py-2 rounded-xl text-xs font-bold bg-gradient-to-r from-teal-500 to-emerald-600 hover:from-teal-600 hover:to-emerald-700 text-white shadow-lg shadow-teal-500/20 transition-all flex items-center gap-1.5"
            >
              <span>🖨️</span>
              <span>Save as PDF / Print</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-xl bg-slate-700/50 hover:bg-rose-500/20 hover:text-rose-400 text-slate-400 transition-colors"
              title="Close Report Preview"
            >
              ✕
            </button>
          </div>
        </div>

        {/* Printable Document Container */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-10 bg-slate-950/40">
          <div
            id="printable-report"
            className="mx-auto max-w-3xl bg-white text-slate-900 p-8 sm:p-12 rounded-2xl shadow-2xl space-y-8 font-sans border border-slate-200"
          >
            {/* Header / Emblem */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center border-b-2 border-slate-900 pb-6 gap-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-teal-600 flex items-center justify-center text-white font-extrabold text-2xl shadow-md">
                  ✚
                </div>
                <div>
                  <h1 className="text-xl sm:text-2xl font-black tracking-tight text-slate-900">
                    MEDTRIAGE AI
                  </h1>
                  <p className="text-xs font-bold text-teal-700 uppercase tracking-widest">
                    Clinical Triage & Referral Summary
                  </p>
                </div>
              </div>

              <div className="text-left sm:text-right text-xs space-y-1">
                <div className="font-mono font-bold bg-slate-100 px-3 py-1 rounded-lg border border-slate-300 inline-block">
                  {refId}
                </div>
                <div className="text-slate-500 font-medium">{timestamp}</div>
              </div>
            </div>

            {/* Severity Alert Banner */}
            {isHighSeverity && (
              <div className="p-4 bg-rose-50 border-2 border-rose-500 rounded-xl flex items-center gap-3 text-rose-900">
                <span className="text-2xl">🚨</span>
                <div>
                  <h4 className="font-extrabold text-sm uppercase tracking-wider">
                    High Urgency Clinical Alert
                  </h4>
                  <p className="text-xs leading-relaxed">
                    The patient's reported symptoms match severe clinical conditions. Immediate physical evaluation by a medical professional or emergency department is strongly advised.
                  </p>
                </div>
              </div>
            )}

            {/* Section 1: Chief Complaint */}
            <div className="space-y-2">
              <h3 className="text-xs font-extrabold uppercase tracking-wider text-slate-500 border-b border-slate-200 pb-1">
                1. Chief Complaint & Reported Symptoms
              </h3>
              <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 text-sm font-medium italic text-slate-800 leading-relaxed">
                "{symptomsInput}"
              </div>
            </div>

            {/* Section 2: Clinical Assessment & Keywords */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-1">
                <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">
                  Triage Urgency Level
                </span>
                <div className="flex items-center gap-2">
                  <span className={`w-3 h-3 rounded-full ${isHighSeverity ? 'bg-rose-500' : 'bg-teal-500'}`}></span>
                  <span className={`font-black text-base uppercase ${isHighSeverity ? 'text-rose-600' : 'text-teal-700'}`}>
                    {topPrediction.severity} Urgency
                  </span>
                </div>
              </div>

              <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-1">
                <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">
                  Detected Symptom Tags
                </span>
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {result.detected_symptoms.length > 0 ? (
                    result.detected_symptoms.map((tag, idx) => (
                      <span
                        key={idx}
                        className="px-2 py-0.5 rounded-md bg-slate-200 text-slate-800 font-bold text-xs capitalize"
                      >
                        #{tag}
                      </span>
                    ))
                  ) : (
                    <span className="text-xs text-slate-500 italic">No specific keywords flagged</span>
                  )}
                </div>
              </div>
            </div>

            {/* Section 3: Vector DB Consensus Diagnoses */}
            <div className="space-y-3">
              <h3 className="text-xs font-extrabold uppercase tracking-wider text-slate-500 border-b border-slate-200 pb-1">
                2. AI Vector DB Differential Diagnoses
              </h3>
              <div className="overflow-hidden border border-slate-200 rounded-xl">
                <table className="w-full text-left border-collapse text-sm">
                  <thead>
                    <tr className="bg-slate-100 border-b border-slate-200 text-slate-700 text-xs font-bold uppercase tracking-wider">
                      <th className="p-3">Rank</th>
                      <th className="p-3">Predicted Condition</th>
                      <th className="p-3">Confidence</th>
                      <th className="p-3">Recommended Specialty</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200 font-medium">
                    {result.predictions.map((pred, idx) => (
                      <tr key={idx} className={idx === 0 ? 'bg-teal-50/50 font-bold' : ''}>
                        <td className="p-3 text-slate-500">#{idx + 1}</td>
                        <td className="p-3 text-slate-900 flex items-center gap-1.5">
                          <span>{pred.disease}</span>
                          {idx === 0 && <span className="text-[10px] bg-teal-600 text-white px-1.5 py-0.5 rounded uppercase font-bold">Primary</span>}
                        </td>
                        <td className="p-3 text-teal-700 font-extrabold">
                          {(pred.confidence * 100).toFixed(1)}%
                        </td>
                        <td className="p-3 text-slate-700">{pred.specialty}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Section 4: Recommended Routing & Specialist */}
            <div className="p-5 bg-indigo-50/60 border-2 border-indigo-200 rounded-xl space-y-2">
              <h4 className="text-xs font-extrabold uppercase tracking-wider text-indigo-900 flex items-center gap-1.5">
                <span>📍 Recommended Clinical Routing</span>
              </h4>
              <p className="text-sm text-indigo-950 font-bold">
                Please present this referral report to: <span className="underline decoration-indigo-500 font-extrabold">{topPrediction.specialty}</span>
              </p>
              <p className="text-xs text-indigo-800 leading-relaxed">
                Note for attending medical staff: This preliminary triage report was generated by comparing patient symptoms against 1,230 validated clinical records in an n-gram TF-IDF vector space.
              </p>
            </div>

            {/* Section 5: Historical Case Evidence */}
            <div className="space-y-2">
              <h3 className="text-xs font-extrabold uppercase tracking-wider text-slate-500 border-b border-slate-200 pb-1">
                3. Historical Case Evidence (Vector Neighbors)
              </h3>
              <div className="space-y-2 text-xs">
                {result.similar_cases.slice(0, 3).map((caseItem, idx) => (
                  <div key={idx} className="p-3 bg-slate-50 rounded-lg border border-slate-200 flex justify-between items-start gap-4">
                    <div>
                      <span className="font-bold text-slate-900">Case #{caseItem.case_id} ({caseItem.disease}):</span>{' '}
                      <span className="text-slate-600 italic">"{caseItem.symptom_text}"</span>
                    </div>
                    <span className="font-mono font-bold text-teal-700 whitespace-nowrap bg-teal-100 px-2 py-0.5 rounded">
                      {(caseItem.similarity * 100).toFixed(1)}% match
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Signature & Footer */}
            <div className="pt-8 border-t-2 border-slate-300 space-y-8">
              <div className="grid grid-cols-2 gap-8 text-xs pt-4">
                <div className="space-y-4">
                  <div className="border-b border-slate-400 pb-1 w-48"></div>
                  <span className="font-bold text-slate-600 uppercase">Patient Signature</span>
                </div>
                <div className="space-y-4">
                  <div className="border-b border-slate-400 pb-1 w-64"></div>
                  <span className="font-bold text-slate-600 uppercase">Attending Doctor / Nurse Signature</span>
                </div>
              </div>

              <div className="text-[10px] text-center text-slate-400 border-t border-slate-200 pt-4 leading-relaxed">
                <strong>MEDTRIAGE AI — CLINICAL TRIAGE SYSTEM</strong> • CONFIDENTIAL & PROPRIETARY HEALTH DATA
                <br />
                Disclaimer: This AI-generated referral report is designed to assist healthcare professionals and streamline patient intake. It does not replace a formal physician examination or clinical diagnosis.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
